# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-05 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0027_auto_20181023_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expedientemateria',
            options={'ordering': ['-sessao_plenaria', 'numero_ordem'], 'verbose_name': 'Matéria do Expediente', 'verbose_name_plural': 'Matérias do Expediente'},
        ),
        migrations.AlterModelOptions(
            name='ordemdia',
            options={'ordering': ['-sessao_plenaria', 'numero_ordem'], 'verbose_name': 'Matéria da Ordem do Dia', 'verbose_name_plural': 'Matérias da Ordem do Dia'},
        ),
        migrations.AlterModelOptions(
            name='registrovotacao',
            options={'ordering': ('-materia', 'ordem', 'expediente'), 'verbose_name': 'Votação', 'verbose_name_plural': 'Votações'},
        ),
    ]
