# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-06 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0028_auto_20181105_1647'),
        ('sessao', '0029_auto_20181024_0952'),
    ]

    operations = [
    ]
