# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-26 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0030_merge_20181106_2043'),
        ('sessao', '0031_auto_20181119_1103'),
    ]

    operations = [
    ]
